### PR TITLE
Docs: Update Apache configs to only support v2.4.0+

### LINKED ISSUE #975: Update docs and remove configs for Apache v2.2.x as its now EOL
From https://httpd.apache.org/#apache-httpd-22-end-of-life-2018-01-01:

> Apache httpd 2.2 End-of-Life 2018-01-01
>
> As previously announced, the Apache HTTP Server Project has discontinued all development and patch review of the 2.2.x series of releases.
>
> The Apache HTTP Server Project had long committed to provide maintenance releases of the 2.2.x flavor through June of 2017, and to continue to publish some security source code patches until December of 2017. The final release 2.2.34 was published in July 2017, and no further evaluation of security risks will be published for 2.2.x releases.

### PR DESCRIPTION
**Pull request by alrra**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/getting-started/pull-requests/#commit-messagess)

For non-trivial changes, please make sure you also:

- [x] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

From https://httpd.apache.org/#apache-httpd-22-end-of-life-2018-01-01:

    Apache httpd 2.2 End-of-Life 2018-01-01

    As previously announced, the Apache HTTP Server Project has
    discontinued all development and patch review of the 2.2.x
    series of releases.

    The Apache HTTP Server Project had long committed to provide
    maintenance releases of the 2.2.x flavor through June of 2017,
    and to continue to publish some security source code patches
    until December of 2017. The final release 2.2.34 was published
    in July 2017, and no further evaluation of security risks will
    be published for 2.2.x releases.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fix #975

### CODE REVIEW

**Comment by molant** [comment]
What's the percentage of servers running 2.2?
Even if it has reached EOL if the number Eric of users is still high I think we should keep the docs. I see it similar to what we do with rules that target old browsers that don't receive any updates.

**Comment by alrra** [comment]
> What's the percentage of servers running 2.2?

It's going to be hard to get accurate data on that.

---

Some data:

<details>
<summary>HTTP archive</summary>

| | Number of <br>requests | Server header value |
|:---|:---|:---|
| 1   |5261593|apache|
| 2   |383646|apache-coyote/1.1|
| 3   |351438|apache/2.2.15 (centos)|
| 4   |258378|apache/2.4.7 (ubuntu)|
| 5   |242514|apache/2|
| 6   |208058|apache/2.4.18 (ubuntu)|
| 7   |196303|apache/2.4.10 (debian)|
| 8   |137030|apache/2.2.22 (debian)|
| 9   |103847|apache/2.2.24 (unix) mod_ssl/2.2.24 openssl/1.0.1e-fips mod_fastcgi/2.4.6|
| 10  |74941|apache/2.4.29|
| 11  |65519|apache/2.2.3 (centos)|
| 12  |61730|apache/2.2.22 (ubuntu)|
| 13  |53829|apache/2.2.15 (red hat)|
| 14  |42641|apache/2.4.25 (debian)|
| 15  |38819|apache/2.4.29 (cpanel) openssl/1.0.2n mod_bwlimited/1.4|
| 16  |35222|apache/2.2.16 (debian)|
| 17  |34307|apache/2.4|
| 18  |31776|apache/2.4.27|
| 19  |30598|apache/2.4.6 (centos) php/5.4.16|
| 20  |29965|apache/2.2.22|
| 21  |20750|apache/2.2.15|
| 22  |19871|apache/2.2.31 (unix) mod_ssl/2.2.31 openssl/1.0.1e-fips mod_bwlimited/1.4|
| 23  |19323|apache/2.4.6 (centos)|
| 24  |19238|apache/2.4.6 (centos) openssl/1.0.1e-fips php/5.4.16|
| 25  |19182|apache/2.4.29 (unix)|
| 26  |19122|apache/2.4.10|
| 27  |18012|apache/2.4.6 (centos) openssl/1.0.2k-fips php/5.4.16|
| 28  |17217|apache phusion_passenger/4.0.10 mod_bwlimited/1.4|
| 29  |17048|apache/2.2.29 (unix) mod_ssl/2.2.29 openssl/1.0.1e-fips mod_bwlimited/1.4|
| 30  |17019|apache/2.2.3 (red hat)|
| 31  |15927|apache/2.4.16 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4|
| 32  |15867|apache/2.4.6|
| 33  |14165|apache/2.2.34 (amazon)|
| 34  |13598|apache/2.4.6 (centos) openssl/1.0.2k-fips|
| 35  |12450|apache/2.4.29 (ubuntu)|
| 36  |11132|apache/2.4.7|
| 37  |11043|apache/2.2.14 (ubuntu)|
| 38  |10941|apache/2.2.22 (@release@)|
| 39  |10931|apache/2.4.18 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4|
| 40  |10220|apache/2.4.6 (centos) openssl/1.0.1e-fips|
| 41  |10150|apache/2.2.31 (amazon)|
| 42  |9819|apache/2.4.18 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9|
| 43  |9748|apache/2.4.6 (centos) openssl/1.0.1e-fips mod_fcgid/2.3.9 php/5.4.16|
| 44  |8911|apache/2.4.25 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4|
| 45  |8840|apache/2.4.27 (amazon) openssl/1.0.2k-fips php/5.6.32|
| 46  |8078|apache/2.2.34 (unix) mod_ssl/2.2.34 openssl/1.0.1e-fips|
| 47  |7943|apache/2.4.25 (ubuntu)|
| 48  |7505|apache/2.2.34 (unix) mod_ssl/2.2.34 openssl/1.0.1e-fips mod_bwlimited/1.4|
| 49  |7098|apache/2.4.23 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4|
| 50  |7055|apache/2.4.6 (centos) openssl/1.0.2k-fips mod_fcgid/2.3.9 php/5.4.16|
| 51  |6587|apache/2.2|
| 52  |6017|apache/2.2.26 (unix)|
| 53  |5900|apache/2.4.10 (ubuntu)|
| 54  |5812|apache/2.4.6 (centos) openssl/1.0.2k-fips php/5.6.33|
| 55  |5482|apache/2.4.25|
| 56  |5473|apache/2.4.27 (amazon)|
| 57  |5163|apache/2.2.29 (unix) mod_ssl/2.2.29 openssl/1.0.1e-fips dav/2 mod_bwlimited/1.4|
| 58  |5135|apache/2.2.27 (unix) mod_ssl/2.2.27 openssl/1.0.1e-fips mod_bwlimited/1.4|
| 59  |5027|apache/2.4.23 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9|
| 60  |4760|apache/2.2.32 (unix) mod_ssl/2.2.32 openssl/1.0.1e-fips mod_bwlimited/1.4|
| 61  |4733|apache/2.2.27 (unix) mod_ssl/2.2.27 openssl/1.0.1e-fips|
| 62  |4612|apache/2.2.15 (oracle)|
| 63  |4434|apache/2.2.12 (linux/suse)|
| 64  |4372|apache/2.4.27 (amazon) php/5.6.32|
| 65  |4357|apache/2.4.18|
| 66  |4229|apache/2.4.6 (centos) openssl/1.0.1e-fips php/5.6.30|
| 67  |4215|apache / zoneos|
| 68  |4188|apache/2.4.29 (unix) openssl/1.0.1e-fips|
| 69  |3999|apache/2.4.27 (ubuntu)|
| 70  |3909|apache/2.4.12 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4|
| 71  |3890|apache/2.2.29 (amazon)|
| 72  |3828|apache/2.4.12 (ubuntu)|
| 73  |3806|apache/2.2.34|
| 74  |3797|apache/2.4.29 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4|
| 75  |3729|apache/2.4.27 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4|
| 76  |3703|apache/2.2.20 (unix) mod_ssl/2.2.20 openssl/0.9.8o|
| 77  |3550|apache/2.2.15 (centos) dav/2 mod_ssl/2.2.15 openssl/1.0.1e-fips|
| 78  |3396|apache/2.2.31 (unix)|
| 79  |3300|apache/2.2.31 (unix) mod_ssl/2.2.31 openssl/1.0.1e-fips dav/2 mod_bwlimited/1.4|
| 80  |3288|apache/2.4.27 (amazon) openssl/1.0.2k-fips php/5.6.33|
| 81  |3255|apache/2.4.6 (centos) php/5.6.30|
| 82  |3246|apache/2.4.6 (centos) openssl/1.0.2k-fips php/7.0.27|
| 83  |3197|apache/2.2.27 (centos)|
| 84  |3079|apache/2.2.22 (ubuntu) mod_ssl/2.2.22 openssl/1.0.1|
| 85  |3063|apache/2.4.16 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9|
| 86  |3018|apache/2.0.63 (unix) mod_ssl/2.0.63 openssl/0.9.8e-fips-rhel5 php/5.2.8|
| 87  |3007|apache/2.2.31|
| 88  |2999|apache/2.4.27 (amazon) openssl/1.0.2k-fips|
| 89  |2987|apache/2.4.16 (ubuntu)|
| 90  |2796|apache/2.2.26 (unix) mod_ssl/2.2.26 openssl/1.0.1e-fips dav/2 mod_bwlimited/1.4|
| 91  |2785|apache/2.4.6 (red hat enterprise linux)|
| 92  |2778|apache/2.4.27 (unix)|
| 93  |2627|apache/2.4.6 (centos) openssl/1.0.2k-fips php/5.6.32|
| 94  |2622|apache/2.4.25 (unix) openssl/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9|
| 95  |2615|apache/2.2.22 (win32) php/5.4.0|
| 96  |2517|apache/2.2.32 (amazon)|
| 97  |2506|apache/2.2.15 (scientific linux)|
| 98  |2487|apache/2.2.22 (el)|
| 99  |2431|apache/2.4.6 (centos) php/5.6.31|
| 100 |2427|apache/2.2.34 (unix)|

Query used:

```sql
select count(requestid) as number_of_requests, lower(resp_server) as server_header_value
from [httparchive:runs.latest_requests]
where REGEXP_MATCH(resp_server, 'Apache')
group by server_header_value
order by number_of_requests desc 
```
</details>

<details>
<summary>W3techs</summary>

According to [this](https://w3techs.com/technologies/details/ws-apache/2/all): `v2.4.x` => `59.7%`, `v2.2.x` => `39.1%` 
</details>

--- 

>  I see it similar to what we do with rules that target old browsers that don't receive any updates.

One important difference from old browsers is that with servers, the site owner(s) can control the update process and they don't rely on millions of other people to upgrade.

>  no further evaluation of security risks will be published for 2.2.x releases.

☝🏻 that is concerning, and I think we shouldn't encourage users to continue to use `2.2.x`.

Also note that:

* Apache `2.4` was first released in 2012.
* The list of changes seems reasonable (see: [`Upgrading to 2.4 from 2.2`](https://httpd.apache.org/docs/trunk/upgrading.html)).
* Current supported version of OSes such as Ubuntu, macOS, default to Apache `2.4.x` (so using `2.2.x` on those systems means you will have to compile from source)

**Comment by molant** [comment]
> the site owner(s) can control the update process and they don't rely on millions of other people to upgrade.

That's only true if you control the whole infrastructure. If you are in a shared host good luck trying to change it.

> I think we shouldn't encourage users to continue to use `2.2.x`.

I don't think that having documentation for that version is encouraging them to use it.

The numbers show that `2.2.x` is still pretty big. IMO we shouldn't remove them for now. One thing we could do is create another rule that checks the `Server` header and warns you if you are using obsolete versions of servers and/or modules. That way we are doing something to let the users know they should update. Maybe it should be part of the headers rule?

**Comment by alrra** [comment]
> That's only true if you control the whole infrastructure. If you are in a shared host good luck trying to change it.

Yes, nobody said it you be easy, but you get my point, it's achievable.

> The numbers show that 2.2.x

The data depends on the number of requests. So, something such as a CDN will have more visibility.

>  IMO we shouldn't remove them for now.

I'm ok with keeping the current configs for the time being, but going forward I'm not planning on keeping the backwards compatibility for the configs.

**Pull request closed without merging**
