### PR TITLE
Fix: Add path to load external rules

### PR DESCRIPTION
**Pull request by qzhou1607**
## Pull request checklist

Make sure you:

- [X] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [X] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/getting-started/pull-requests/#commit-messagess)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

### CODE REVIEW

**Comment by qzhou1607** [comment]
@molant Nope, it doesn't work without the `dist` part.

**Comment by molant** [comment]
What are the files under `process.cwd()`? Also, can you paste the `package.json` of the project?

**Comment by qzhou1607** [comment]
@molant  Under `process.cwd()` are `dist`, `node_modules`, `src`, `tests`, `package.json`, `.sonarwharc` and etc. When I run the external rules like `jsll`, I cd to `jsll` folder first and ran `node node_modules\sonarwhal\dist\src\bin\sonarwhal.js ${url}` inside the `jsll` folder. And the package.json content is as below.
```
{
  "author": "Microsoft",
  "ava": {
    "babel": {
      "presets": []
    },
    "concurrency": 5,
    "failFast": false,
    "files": [
      "dist/tests/**/*.js"
    ],
    "timeout": "1m"
  },
  "dependencies": {
    "locale-code": "^1.1.1"
  },
  "description": "sonarwhal rule to validate Microsoft's JSLL configuration.",
  "devDependencies": {
    "ava": "^0.25.0",
    "cpx": "^1.5.0",
    "eslint": "^4.18.2",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-markdown": "^1.0.0-beta.7",
    "eslint-plugin-typescript": "^0.9.0",
    "express": "^4.16.2",
    "lodash.clonedeep": "^4.5.0",
    "markdownlint-cli": "^0.7.0",
    "npm-link-check": "^2.0.0",
    "npm-run-all": "^4.1.2",
    "nyc": "^11.4.1",
    "rimraf": "^2.6.2",
    "sonarwhal": "^0.27.0",
    "typescript": "^2.6.2",
    "typescript-eslint-parser": "^14.0.0"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "files": [
    "dist/src",
    "npm-shrinkwrap.json"
  ],
  "homepage": "https://sonarwhal.com",
  "keywords": [
    "jsll",
    "sonarwhal",
    "sonarwhal-rule",
    "jsll",
    "jsll-rule"
  ],
  "license": "Apache-2.0",
  "main": "dist/src/index.js",
  "name": "@sonarwhal/rule-jsll",
  "peerDependencies": {
    "sonarwhal": "^0.27.0"
  },
  "scripts": {
    "build": "npm run clean && npm-run-all build:*",
    "build-release": "npm run clean && npm run build:assets && tsc --inlineSourceMap false --removeComments true",
    "build:assets": "cpx \"./{src,tests}/**/{!(*.ts),.!(ts)}\" dist",
    "build:ts": "tsc",
    "clean": "rimraf dist",
    "lint": "npm-run-all lint:*",
    "lint:js": "eslint . --cache --ext js --ext md --ext ts --ignore-path .eslintignore --report-unused-disable-directives",
    "lint:md": "markdownlint --ignore CHANGELOG.md *.md",
    "test": "npm run lint && npm run build && nyc ava",
    "watch": "npm run build && npm-run-all --parallel -c watch:*",
    "watch:assets": "npm run build:assets -- -w --no-initial",
    "watch:test": "ava --watch",
    "watch:ts": "npm run build:ts -- --watch"
  },
  "repository": "Microsoft/sonarwhal-microsoft-rules",
  "version": "0.1.0"
}
```

**Comment by molant** [comment]
I don't get why it doesn't work with the `package.json` in there pointing to the right `main` 😞

Let's get this merge then.

**Comment by qzhou1607** [comment]
@molant Ah sorry I misunderstood you. You meant remove `/dist/src/index.js` all that but only use `process.cwd()`, right? I tried again and that works. I will make another PR, sorry for the misunderstanding.

**Pull request merged**
