### PR TITLE
Docs: Fix typo in `options.ts`

### PR DESCRIPTION
**Pull request by frvge**
- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests/#commitmessages)

Fix a typo in CLI description

### CODE REVIEW

**Comment by alrra** [comment]
@frvge Thank you for this pull request!  

Can you also [follow the instructions in the previous comment](https://github.com/sonarwhal/sonarwhal/pull/776#issuecomment-360124463), and then sign the CLA? Thanks!

**Comment by frvge** [comment]
I see "You have signed the CLA for sonarwhal/sonarwhal". i just added my work email to my Github account, so maybe that was it =/

**Comment by alrra** [comment]
> I see "You have signed the CLA for sonarwhal/sonarwhal".

Maybe it's a bug? (Cc: @kborchers)

---

Thank you for the pull request, and congratulations on your first contribution to `sonarwhal`! 🎉

**Comment by kborchers** [comment]
There is a bug, or really more of a design flaw, in the checker that only checks the primary email on the account that signs the CLA. So, if @frvge signed the CLA with a GitHub account where the primary email is personal but the commit email is a work email, the bot will not see the CLA as signed even if the work email is added to the account. I can verify that @frvge does appear in the signature database.

Please feel free to file an issue at https://github.com/JSFoundation/cla-assistant which is our, unfortunately, very outdated fork of cla-assistant. Any help bringing that fork in line with upstream and fixing issues like these would be very much appreciated!

**Pull request closed without merging**
