### PR TITLE
Update tests and update event for target url to `fetch::end::{type}`

### PR DESCRIPTION
**Pull request by sarvaje**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/getting-started/pull-requests/#commit-messagess)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

**Comment by molant** [comment]
image

🤣

**Comment by molant** [comment]
The test suite passes with this change but we should verify a few more things to make sure everything works as expected. I've talked with @sarvaje and we should at least do the following:

* Remove the `isHTMLDocument` checks we have in some of the rules (like `meta-charset-utf-8`). If we are doing that check in another event other than `fetch::end::html` then we need to know why. For example, for `meta-charset-utf-8` we subscribe to `traverse::end` which should only be sent after traversing a document (what happens if we pass a text file as target? maybe we need to rely on the content type)
* We should add tests to all the rules that subscribe to `traverse::end::html` and send something as the target that's not an HTML document. E.g.: `sslllabs`, `meta-charset-utf-8`, etc. We shouldn't receive any errors but we need to verify this.
* something else?

@sarvaje, @alrra any other things we should check?

**Comment by sarvaje** [comment]
hahahaha, I don't know why the show the commit message like that hahahahaha

**Comment by sarvaje** [comment]
>We should add tests to all the rules that subscribe to traverse::end::html and send something as the target that's not an HTML document. E.g.: sslllabs, meta-charset-utf-8, etc. We shouldn't receive any errors but we need to verify this.

`fetch::end::html`

**Comment by sarvaje** [comment]
@molant this is ready to review again

**Comment by alrra** [comment]
Closing as this PR is not merged in the [`hint`](https://github.com/sonarwhal/sonarwhal/commits/hint) branch.

**Pull request closed without merging**
